# Generated by Django 4.2.7 on 2023-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Dob', models.DateField()),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'male')], max_length=11)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('courses', models.CharField(max_length=250)),
                ('enquiry', models.CharField(max_length=250)),
            ],
        ),
    ]
